def main_display():
    print("////////////////////////////")
    print("-------System Menu----------")
    print("1. Create Trainer")
    print("2. Load Trainer")
    print("3. View Trainer")
    print("4. Capture Pokemon")
    print("5. Release Pokemon")
    print("6. Delete Trainer")
    print("7. Quit System")
    print("----------------------------")
    print("////////////////////////////")